# -*- coding: utf-8 -*-
"""Track-Cell-number.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iK2vteiBiviIT-1d-dANCnJvxw6jEGY_
"""



pip install phonenumbers

"""Create a phone number to start the search"""

Trace_number = "+17542104553"

import phonenumbers
from phonenumbers import geocoder
ch_num = phonenumbers.parse(Trace_number, "CH")
print(geocoder.description_for_number(ch_num, "en"))

"""CH = county history;
en = language "English"
"""

Find the service provider

from phonenumbers import carrier
ch_num = phonenumbers.parse(Trace_number, "RO")
print(carrier.name_for_number(ch_num, "en"))